# Generated by Django 5.1.4 on 2025-01-08 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_busquedalaboral_alter_habitacion_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busquedalaboral',
            options={'verbose_name': 'Búsqueda Laboral', 'verbose_name_plural': 'Búsquedas Laborales'},
        ),
        migrations.AlterModelOptions(
            name='habitacion',
            options={'verbose_name': 'Habitación', 'verbose_name_plural': 'Habitaciones'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AddField(
            model_name='habitacion',
            name='temporada',
            field=models.CharField(choices=[('Verano', 'Verano'), ('Invierno', 'Invierno')], default='Verano', max_length=10, verbose_name='Temporada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='temporada',
            field=models.CharField(choices=[('Verano', 'Verano'), ('Invierno', 'Invierno')], default='Verano', max_length=10, verbose_name='Temporada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='busquedalaboral',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='busquedalaboral',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='busquedalaboral',
            name='fecha_publicacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Publicación'),
        ),
        migrations.AlterField(
            model_name='busquedalaboral',
            name='puesto',
            field=models.CharField(max_length=100, verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='busquedalaboral',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='numero',
            field=models.IntegerField(unique=True, verbose_name='Número de Habitación'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(choices=[('Doble_Estandar', 'Doble Estándar'), ('Doble_Superior', 'Doble Superior'), ('Single_Estandar', 'Single Estándar'), ('Single_Superior', 'Single Superior')], max_length=20, verbose_name='Tipo de Habitación'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=20, verbose_name='Estado de la Reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_entrada',
            field=models.DateField(verbose_name='Fecha de Entrada'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_salida',
            field=models.DateField(verbose_name='Fecha de Salida'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.habitacion', verbose_name='Habitación'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
