# Generated by Django 5.1.4 on 2025-01-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusquedaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(choices=[('Doble_Estandar', 'Doble Estandar'), ('Doble_Superior', 'Doble Superior'), ('Single_Estandar', 'Single Estandar'), ('Single_Superior', 'Single Superior')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=20),
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
